version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn StackOfMusic.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"

